#!/usr/bin/env ferite
uses "console", "array", "expr.fe";

Console.println(argv);

if( Array.size(argv)<1 ) {
   Console.println( "expr: missing operand" );
   return;

   // This is a script!  There is no function main(), so I don't know
   // if this will work... argv is not "received," so can we really
   // return?  What kind of scope are we actually in here?
}

Console.println( Expr.expr(argv) );

// End of program.
